feeder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('feeds.urls')),
    url(r'^admin/', admin.site.urls),
]

feeds/urls.py
from django.conf.urls import url
from . import views

app_name = 'feeds'

urlpatterns = [
    url(r'^authors.json$', views.AuthorsListView.json_response, name='authors_list_json'),
    url(r'^feed/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/$', views.FeedArticlesListView.as_view(), name='feed_article_list'),
    url(r'^author/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/$', views.AuthorArticlesListView.as_view(), name='author_article_list'),
    url(r'^articles/?$', views.ArticleListView.as_view(), name='articles_list'),
    url(r'^authors/?$', views.AuthorsListView.as_view(), name='authors_list'),
    url(r'^feeds/?$', views.FeedListView.as_view(), name='feeds_list'),
    url(r'^$', views.HomePageView.as_view(), name='home'),
]

feeds/models.py
from django.db import models

# Create your models here.
class ActiveEntry(models.Manager):
    def get_queryset(self):
        return super(ActiveEntry, self).get_queryset().filter(is_active=True)

class Feed(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    url = models.URLField(max_length=250, verbose_name="URL")
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    last_fetch = models.DateTimeField(null=True)

    objects = models.Manager()
    active_feeds = ActiveEntry()

    class Meta:
        ordering = ['title']
        unique_together = ('title', 'url')

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Article(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    url = models.URLField(max_length=250, verbose_name="URL")
    published = models.DateTimeField()
    img_url = models.URLField(blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published_articles = ActiveEntry()

    class Meta:
        ordering = ['-published']
        unique_together = ('feed', 'url')

    def __str__(self):
        return self.title

feeds/forms.py
from django.forms import ModelForm
from .models import Feed

class FeedForm(ModelForm):
    class Meta:
        model = Feed
        fields = ('title', 'url')

feeds/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView

from .models import Feed, Author, Article
from .forms import FeedForm

import json

# Form for source/feed submission
class FeedFormView(FormView):
    form_class = FeedForm

    def feed_form(self):
        return FeedForm()

    def post(self, request, **kwargs):
        form = FeedForm(request.POST)
        if form.is_valid():
            new_feed = form.save(commit=False)
            new_feed.slug = slugify(new_feed.title)
            new_feed.save()
            self.object_list = self.get_queryset()
            return self.render_to_response(super(FeedFormView, self).get_context_data(**kwargs))
        else:
            self.object_list = self.get_queryset()
            return self.render_to_response(super(FeedFormView, self).get_context_data(**kwargs))

# Homepage View
class HomePageView(FeedFormView, ListView):
    queryset = Feed.active_feeds.all().order_by('title')
    template_name = 'feeds/homepage.html'

# Display all sources/feeds
class FeedListView(ListView):
    queryset = Feed.active_feeds.all().order_by('title')
    context_object_name = 'feeds'
    template_name = 'feeds/feed/feeds_list.html'

# Display all authors
class AuthorsListView(ListView):
    queryset = Author.objects.all().order_by('name')
    template_name = 'feeds/feed/authors_list.html'
    paginate_by = 20

    def json_response(request):
        if request.method == 'POST':
            authors = Author.objects.all().filter(name__contains=str(request.POST['search'])).order_by('name')
            data = [{
                "value": item.name,
                "name": item.name,
                "search": item.name,
                "url": "/author/{0}/{1}".format(item.id, item.slug)
            } for item in authors]
            return HttpResponse(json.dumps(data), content_type='application/json')

# Display all articles
class ArticleListView(ListView):
    queryset = Article.published_articles.all().order_by('-published')
    template_name = 'feeds/feed/article_list.html'
    context_object_name = 'articles'
    paginate_by = 20

    def active_feeds(self):
        return Feed.active_feeds.all().order_by('title')

# Display articles from one source/feed
class FeedArticlesListView(ListView):
    template_name = 'feeds/feed/article_list.html'
    paginate_by = 20

    def active_feeds(self):
        return Feed.active_feeds.all().order_by('title')

    def get_queryset(self):
        self.feed = get_object_or_404(Feed, id=self.kwargs['id'])
        return Article.published_articles.filter(feed=self.feed).order_by('-published')

# Display articles from one author
class AuthorArticlesListView(ListView):
    template_name = 'feeds/feed/article_list.html'
    paginate_by = 20

    def active_feeds(self):
        return Feed.active_feeds.all().order_by('title')

    def get_queryset(self):
        self.author = get_object_or_404(Author, id=self.kwargs['id'])
        return Article.published_articles.filter(author=self.author).order_by('-published')

feeds/templates/feeds/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | Feeder</title>
  <link href="{% static "css/uikit.gradient.min.css" %}" rel="stylesheet">
  <link href="{% static "css/custom.css" %}" rel="stylesheet">
</head>
<body>

  <div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">

    {% include "feeds/navigation.html" %}

    <div class="uk-grid">
      {% block content %}
      {% endblock %}
    </div><!-- .uk-grid -->
  </div>

  <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
  <script src="{% static "js/uikit.min.js" %}"></script>
  <script src="{% static "js/components/autocomplete.js" %}"></script>

</body>
</html>

feeds/templates/feeds/feed/article_list.html
{% extends "feeds/base.html" %}

{% block title %}Articles{% endblock %}

{% block content %}

  <div class="article-wrapper uk-width-4-5">
    {% if object_list %}

      {% for article in object_list %}
        <article class="uk-article uk-panel">

          <p class="uk-article-meta">
            <a href="{% url 'feeds:feed_article_list' article.feed.id article.feed.slug %}">{{ article.feed }}</a> /
            {% if article.author.id %} <a href="{% url 'feeds:author_article_list' article.author.id article.author.slug %}">{{ article.author }}</a> / {% endif %}
            Published on {{ article.published }}
          </p>

          <div class="article-container">
            <div class="article-thumb">
            {% if article.img_url %}
              <img src="{{ article.img_url }}">
            {% else %}
              <img src="https://placehold.it/100x66">
            {% endif %}
            </div>
            <h1 class="uk-article-title"><a href="{{ article.url }}" target="_blank">{{ article.title }}</a></h1>
          </div>

        </article>
      {% endfor %}

      {% if is_paginated %}
        {% include "feeds/pagination.html" %}
      {% endif %}

    {% else %}
      <p>No articles found!</p>
    {% endif %}
  </div>

  <div class="uk-width-1-5">
    <h3>Active feeds</h3>
    {% include "feeds/feed/feeds_list_side.html" with feeds=view.active_feeds %}
  </div>

{% endblock %}

feeds/templates/feeds/feed/authors_list.html
{% extends "feeds/base.html" %}

{% block title %}Authors{% endblock %}

{% block content %}

  <div class="uk-width-1-1">
    <h1>Authors</h1>

    {% if object_list %}

      <h2 class="tm-article-subtitle">Search for an author:</h2>

      <div class="uk-container-center custom-autocomplete">
        <div class="uk-autocomplete uk-form" data-uk-autocomplete="{source:'/authors.json'}">
          <input class="custom-input" type="text">
          {% csrf_token %}
          {% verbatim %}
          <script type="text/autocomplete">
              <ul class="uk-nav uk-nav-autocomplete uk-autocomplete-results">
                  {{~items}}
                  <li data-value="{{ $item.name }}"><a href="{{ $item.url }}">{{ $item.name }}</a></li>
                  {{/items}}
              </ul>
          </script>
          {% endverbatim %}
        </div>
      </div>

      <ul class="uk-list uk-list-striped">
      {% for author in object_list %}
        <li><a href="{% url 'feeds:author_article_list' author.id author.slug %}">{{ author.name }}</a></li>
      {% endfor %}
      </ul>

      {% if is_paginated %}
        {% include "feeds/pagination.html" %}
      {% endif %}

    {% else %}
      <p>No authors found!</p>
    {% endif %}
  </div>

{% endblock %}

feeds/templates/feeds/feed/feeds_list.html
{% extends "feeds/base.html" %}

{% block title %}Active Feeds{% endblock %}

{% block content %}

  <div class="uk-width-1-1">
    <h1>Active feeds</h1>

    {% if object_list %}

      <ul class="uk-list uk-list-striped">
      {% for feed in object_list %}
        <li><a href="{% url 'feeds:feed_article_list' feed.id feed.slug %}">{{ feed.title }}</a></li>
      {% endfor %}
      </ul>

    {% else %}
      <p>No active feeds found!</p>
    {% endif %}
  </div>

{% endblock %}

feeds/templates/feeds/feed/feeds_list_side.html
{% if feeds %}
  <ul class="uk-list uk-list-striped">
  {% for feed in feeds %}
    <li><a href="{% url 'feeds:feed_article_list' feed.id feed.slug %}">{{ feed.title }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No active feeds found!</p>
{% endif %}

feeds/templates/feeds/form.html
<form action="/" method="POST" class="uk-form uk-form-stacked">
  {% for field in form %}
      <div class="uk-form-row">
          {{ field.errors }}
          <label class="uk-form-label" for="form-s-it">{{ field.label_tag }}</label>
          <div class="uk-form-controls">{{ field }}</div>
      </div>
  {% endfor %}
  {% csrf_token %}
  <p><button class="uk-button">Submit</button></p>
</form>

feeds/templates/feeds/homepage.html
{% extends "feeds/base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}

  <div class="uk-width-4-5">
    <h1>Active feeds</h1>
    {% if object_list %}
      <ul class="uk-list uk-list-striped">
      {% for feed in object_list %}
        <li><a href="{% url 'feeds:feed_article_list' feed.id feed.slug %}">{{ feed.title }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No active feed found!</p>
    {% endif %}
  </div>

  <div class="uk-width-1-5">
    <div class="uk-panel uk-panel-header uk-width-medium-1-1">
      <h2 class="uk-panel-title">Add your feed</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
      {% include "feeds/form.html" with form=view.feed_form %}
    </div>
  </div>

{% endblock %}

feeds/templates/feeds/navigation.html
<nav class="uk-navbar uk-margin-large-bottom">
  <a class="uk-navbar-brand uk-hidden-small" href="/">Feeder</a>
  <ul class="uk-navbar-nav uk-hidden-small">
    <li><a href="/articles/">Articles</a></li>
    <li><a href="/feeds/">Feeds</a></li>
    <li><a href="/authors/">Authors</a></li>
  </ul>
  <a href="#offcanvas" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>
  <div class="uk-navbar-brand uk-navbar-center uk-visible-small">Feeder</div>
</nav>

feeds/templates/feeds/pagination.html
<ul class="uk-pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="uk-icon-angle-double-left"></i></a></li>
    {% endif %}

    <li class="uk-active"><span>{{ page_obj.number }}</span></li>

    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}"><i class="uk-icon-angle-double-right"></i></a></li>
    {% endif %}
</ul>